# Generated by Django 4.2.2 on 2023-08-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
