# Generated by Django 4.2.2 on 2023-08-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubepost",
            name="video_url",
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
