# Generated by Django 4.2.2 on 2023-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0003_alter_youtubepost_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubepost",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
