# Generated by Django 4.2.2 on 2023-08-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_board", "0002_event_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=None),
        ),
    ]
