# Generated by Django 4.2.2 on 2023-08-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notice_images/"),
        ),
        migrations.AddField(
            model_name="notice",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
