# Generated by Django 4.2.2 on 2023-08-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice_board", "0005_alter_notice_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
